from __future__ import annotations

from ._one_turn_geometry_build_support import (
    test_finalize_solids_compacts_tx_vertical_zx_bridge_names_for_long_design_id,
    test_finalize_solids_connects_stacked_tx_dd_right_half_with_hex_vias,
    test_finalize_solids_creates_zx_tx_vertical_external_stubs,
    test_finalize_solids_places_stacked_tx_dd_right_half_vias_between_copper_layers,
    test_finalize_solids_rejects_tx_vertical_mode1_link_when_inward_x_shift_is_ambiguous,
    test_finalize_solids_supports_one_turn_tx_dd_geometry,
    test_finalize_solids_uses_single_hex_via_per_site_when_trace_is_thin,
)
