from __future__ import annotations

from .placement_behavior import (
    _build_polarity,
    _coil_instance_offset,
    _endpoint_z_center,
    _group_endpoint_key,
    _coil_polarity_key,
    _instance_side,
    _mount_allows_instance,
    _rx_dd_center_offset_y,
    _txdd_right_layer_rank_by_z,
    _validate_rxdd_single_layer_count,
)
from .placement_geometry import (
    _axis_aligned_segments_intersect_2d,
    _build_txdd_right_points_a_to_d,
    _build_txdd_right_points_a_to_d_multi_turn,
    _build_txdd_right_points_a_to_d_one_turn,
    _build_txdd_right_points_c_to_a,
    _build_txdd_right_points_c_to_a_one_turn,
    _current_direction_from_xy_points,
    _edge_points_at_xy_terminal,
    _find_txdd_right_inner_c_index,
    _max_feasible_turns,
    _orientation,
    _point_on_segment,
    _required_pair_spacing_mm,
    _segments_intersect_2d,
    _validate_txdd_right_points,
)
from .placement_projection import (
    _build_rxdd_right_points_A_to_d_cw,
    _build_yz_dd_half_from_local,
    _build_yz_dd_pair_from_right_local,
)
from .placement_shared import (
    _normalize_layer_index_for_shared,
    _normalize_optional_int,
    _resolve_txdd_counts,
)
from .placement_txdd import (
    _extend_endpoints,
    _realized_txdd_geometry,
    _txdd_half_topology,
    _txdd_right_points,
    _txdd_right_topology,
    _tx_dd_center_y_and_layer,
)
from .placement_types import (
    PlacementKernelInput,
    PlacementKernelOutput,
    _GroupInstanceKey,
    _Point2,
    _Point3,
    _TxDdRightLocalTopology,
    _UNSET,
    _YzDdPairPlacement,
)


__all__ = [
    "PlacementKernelInput",
    "PlacementKernelOutput",
    "_GroupInstanceKey",
    "_Point2",
    "_Point3",
    "_TxDdRightLocalTopology",
    "_UNSET",
    "_YzDdPairPlacement",
    "_normalize_optional_int",
    "_normalize_layer_index_for_shared",
    "_resolve_txdd_counts",
    "_axis_aligned_segments_intersect_2d",
    "_orientation",
    "_point_on_segment",
    "_segments_intersect_2d",
    "_find_txdd_right_inner_c_index",
    "_build_txdd_right_points_c_to_a",
    "_build_txdd_right_points_c_to_a_one_turn",
    "_build_txdd_right_points_a_to_d_one_turn",
    "_build_txdd_right_points_a_to_d_multi_turn",
    "_build_txdd_right_points_a_to_d",
    "_validate_txdd_right_points",
    "_edge_points_at_xy_terminal",
    "_required_pair_spacing_mm",
    "_realized_txdd_geometry",
    "_build_rxdd_right_points_A_to_d_cw",
    "_build_yz_dd_pair_from_right_local",
    "_build_yz_dd_half_from_local",
    "_tx_dd_center_y_and_layer",
    "_max_feasible_turns",
    "_coil_instance_offset",
    "_validate_rxdd_single_layer_count",
    "_rx_dd_center_offset_y",
    "_mount_allows_instance",
    "_instance_side",
    "_build_polarity",
    "_group_endpoint_key",
    "_coil_polarity_key",
    "_endpoint_z_center",
    "_current_direction_from_xy_points",
    "_extend_endpoints",
    "_txdd_right_points",
    "_txdd_half_topology",
    "_txdd_right_topology",
    "_txdd_right_layer_rank_by_z",
]
