from __future__ import annotations

from ._one_turn_geometry_build_support import (
    test_back_connect_stub_pair_bridge_builds_minus_x_yz_sheet_for_rx_dd,
    test_finalize_solids_keeps_rx_port_reference_on_c_stub_when_sources_are_reversed,
    test_finalize_solids_routes_rx_port_over_a_to_c_and_pair_connector_over_d_to_b,
    test_resolve_rx_dd_port_edges_from_back_faces_fails_on_zero_peer_offset,
    test_resolve_rx_dd_port_edges_from_back_faces_prefers_y_side_on_tie,
    test_resolve_rx_dd_port_edges_from_back_faces_selects_y_side_for_y_dominant_gap,
    test_resolve_rx_dd_port_edges_from_back_faces_selects_z_side_for_z_dominant_gap,
    test_rx_dd_builder_supports_one_turn,
    test_rxdd_connect_landing_segment_fails_on_zero_centerline,
    test_rxdd_connect_landing_segment_is_trace_wide_and_midpoint_centered,
    test_rxdd_connect_sheet_points_fail_on_trace_mismatch,
    test_rxdd_connect_sheet_points_keep_trace_width_and_deterministic_ordering,
    test_stub_center_from_anchor_shifts_box_center_inward_by_half_trace,
)
