from __future__ import annotations

from ._one_turn_geometry_build_support import (
    test_assert_stacked_tx_dd_half_conductors_closed_rejects_ununited_layers,
    test_assert_tx_conductor_graph_common_rejects_extra_external_edges,
    test_finalize_solids_rejects_single_layer_txdd_to_tx_vertical_section_bridge_fallback,
    test_tx_dd_builder_names_stacked_center_protrusions_as_via_tabs_with_2w_length,
    test_tx_dd_builder_records_right_only_sources_for_stacked_four_layer_case,
    test_tx_dd_builder_supports_one_turn_and_keeps_distinct_terminals,
    test_tx_dd_one_turn_a_to_d_raises_when_compact_geometry_would_be_required,
)
