from __future__ import annotations

from ._one_turn_geometry_build_support import (
    test_finalize_solids_assigns_txdd_in_out_stub_roles_from_semantic_feed_bindings,
    test_finalize_solids_does_not_attempt_tx_port_capture_without_semantic_binding,
    test_finalize_solids_orders_tx_stub_creation_by_geometry_not_creation_order_without_semantic_binding,
    test_finalize_solids_skips_tx_port_without_semantic_binding,
)
