from __future__ import annotations

from ._one_turn_geometry_build_support import (
    test_create_hfss_session_rejects_invalid_manifest_ansys_path,
    test_create_hfss_session_uses_manifest_ansys_path_and_avoids_project_rename_path,
    test_create_major_device_groups_raises_when_group_creation_returns_false,
    test_safe_unite_raises_when_unite_returns_false,
    test_tx_vertical_builder_rejects_turn_count_above_three_even_if_feasible,
    test_tx_vertical_builder_skips_non_host_board_without_zx_series_capture,
    test_tx_vertical_builder_supports_one_turn,
)

