"""
This type stub file was generated by pyright.
"""

"""Provides functions for performing common checks."""
def install_message(target: str) -> str:
    """"""
    ...

ERROR_GRAPHICS_REQUIRED = ...
__GRAPHICS_AVAILABLE = ...
def min_aedt_version(min_version: str): # -> Callable[..., Callable[..., Any]]:
    """Compare a minimum required version to the current AEDT version.

    This decorator should only be used on methods where the associated object can reach the desktop instance.
    Otherwise, there is no way to check version compatibility and an error is raised.

    Parameters
    ----------
    min_version: str
        Minimum AEDT version required by the method.
        The value should follow the format YEAR.RELEASE, for example '2025.1'.

    Raises
    ------

    AEDTRuntimeError
        If the method version is higher than the AEDT version.
    """
    ...

def check_graphics_available(warning: bool = ...): # -> None:
    """Check if graphics are available."""
    ...

def graphics_required(method): # -> Callable[..., Any]:
    """Decorate a method as requiring graphics.

    Parameters
    ----------
    method : callable
        Method to decorate.

    Returns
    -------
    callable
        Decorated method.
    """
    ...

