from __future__ import annotations

from ._run_script_artifacts_support import (
    test_build_all_targets_fails_on_missing_manifest_and_stops_immediately,
    test_build_all_targets_fails_when_all_manifests_are_missing,
    test_build_all_targets_with_options_forwards_runtime_controls,
    test_build_all_targets_with_options_rejects_stop_on_error_false,
    test_build_debug_processes_full_manifest_sequentially,
    test_build_entries_forces_sequential_gui_visible_mode,
    test_build_entries_rejects_stop_on_error_false,
    test_build_non_debug_uses_process_pool_path,
    test_build_script_defaults_follow_first_batch_seed_window,
    test_build_script_iterates_default_build_targets_from_sample_profiles,
    test_build_helper_cleans_failed_design_artifacts_and_aedtresults,
    test_build_helper_uses_toml_stem_for_aedt_and_cleans_aedtresults,
    test_sample_build_reuses_build_target_runner_and_skips_sampling,
)

