"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional, Tuple, Union
from ansys.aedt.core.generic.general_methods import pyaedt_function_handler

"""Download example datasets from https://github.com/ansys/example-data"""
EXAMPLES_DATA_REPO = ...
EXAMPLES_PATH = ...
def delete_downloads(): # -> None:
    """Delete all downloaded examples to free space or update the files."""
    ...

@pyaedt_function_handler(destination="local_path")
def download_aedb(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of AEDB file and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example folder containing example files.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_aedb()
    >>> path
    r'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/ANSYS-HSD_V1.aedbb'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_edb_merge_utility(force_download: bool = ..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of WPF Project which allows to merge 2aedb files.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    force_download : bool
        Force to delete cache and download files again.
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_edb_merge_utility(force_download=True)
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/wpf_edb_merge/merge_wizard.py'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_netlist(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of netlist File and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_netlist()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/netlist_small.cir'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_antenna_array(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of Antenna Array and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------

    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_antenna_array()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/FiniteArray_Radome_77GHz_3D_CADDM.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_sbr(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of SBR+ Array and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_antenna_array()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/sbr/Cassegrain.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_sbr_time(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of SBR+ Time domain animation and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_sbr_time()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/sbr/poc_scat_small.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_icepak(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of Icepak Array and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_icepak()
    >>> pathavoid
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/Graphic_Card.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_icepak_3d_component(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of Icepak Array and return the def pathsw.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to PCBAssembly the example file.
    str
        Path to QFP2 the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path1, path2 = ansys.aedt.core.examples.downloads.download_icepak_3d_component()
    >>> path1
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/PCBAssembly.aedt'
    >>> path2
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/QFP2.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_via_wizard(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of Hfss Via Wizard and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_via_wizard()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/viawizard_vacuum_FR4.aedt'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_touchstone(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of touchstone File and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_touchstone()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/SSN_ssn.s6p'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_sherlock(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of sherlock needed files and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_sherlock()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/sherlock'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_leaf(local_path: Optional[Union[str, Path]] = ...) -> Tuple[str, str]:
    """Download an example of Nissan leaf files and return the def path.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    (str, str)
        Path to the 30DH_20C_smooth and BH_Arnold_Magnetics_N30UH_80C tabular material data file file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_leaf(r"c:\temp")
    >>> path
    ('C:/temp/30DH_20C_smooth.tab', 'C:/temp/BH_Arnold_Magnetics_N30UH_80C.tab')
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_custom_reports(force_download: bool = ..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of CISPR25 with customer reports json template files.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    force_download : bool
        Force to delete cache and download files again.
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example folder containing all example files.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_custom_reports(force_download=True)
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/custom_reports'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_3dcomponent(force_download=..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of 3d component array with json template files.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    force_download : bool
        Force to delete cache and download files again.
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example folder containing all example files.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_3dcomponent(force_download=True)
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/array_3d_component'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_fss_3dcomponent(force_download=..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of 3d component array with json template files.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    force_download : bool
        Force to delete cache and download files again.
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example folder containing all example files.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_FSS_3dcomponent(force_download=True)
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/fss_3d_component'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_multiparts(local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download an example of 3DComponents Multiparts.

    If example files have already been downloaded, the download is
    skipped.

    Parameters
    ----------
    local_path : str or :class:`pathlib.Path`, optional
        Path for downloading files. The default is the user's temp folder.

    Returns
    -------
    str
        Path to the example file.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_multiparts()
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/multiparts/library'
    """
    ...

@pyaedt_function_handler(destination="local_path")
def download_twin_builder_data(file_name: Optional[str] = ..., force_download=..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download a Twin Builder example data file.

    Examples files are downloaded to a persistent cache to avoid
    downloading the same file twice.

    Parameters
    ----------
    file_name : str, optional
        Name of the file to download. If not specified, all files in the folder.
    force_download : bool, optional
        Force to delete file and download file again. Default value is ``False``.
    local_path : str or :class:`pathlib.Path`, optional
        Path to download files to. The default is the user's temporary folder.

    Returns
    -------
    str
        Path to the folder containing all Twin Builder example data files.

    Examples
    --------
    Download an example result file and return the path of the file.
    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_twin_builder_data(force_download=True)
    >>> path
    'C:/Users/user/AppData/Local/Temp/PyAEDTExamples/twin_builder'
    """
    ...

@pyaedt_function_handler(filename="name", directory="source")
def download_file(source: str, name: Optional[str] = ..., local_path: Optional[Union[str, Path]] = ...) -> str:
    """Download a file or files from the online examples repository.

    Files are downloaded from the
    :ref:`example-data<https://github.com/ansys/example-data/tree/main/pyaedt>`_ repository
    to a local destination. If ``name`` is not specified, the full directory path
    will be copied to the local drive.

    Parameters
    ----------
    source : str
        Directory name in the Ansys ``example-data`` repository from which the example
        data is to be retrieved. If the ``pyaedt/`` prefix
        is not part of ``directory`` the path will be automatically prepended.
    name : str, optional
        File name to download. By default all files in ``directory``
        will be downloaded.
    local_path : str or :class:`pathlib.Path`, optional
        Path where the files will be saved locally. Default is the user temp folder.

    Returns
    -------
    str
        Path to the local example file or folder.

    Examples
    --------
    Download an example result file and return the path of the file.

    >>> import ansys.aedt.core
    >>> path = ansys.aedt.core.examples.downloads.download_file("motorcad", "IPM_Vweb_Hairpin.mot")
    >>> path
    'C:/Users/user/AppData/local/temp/PyAEDTExamples/motorcad/IPM_Vweb_Hairpin.mot'
    """
    ...

def unzip(source_filename, dest_dir): # -> None:
    ...

