from __future__ import annotations

from pathlib import Path
from typing import Literal, cast

from peetsfea.aedt import Hfss, Modeler3D
from peetsfea.types.manifest import CadProbe, CoilPolaritySpec, EmPortAssignments, EmPorts, GroupObjects, RegionViolation

from ..build_state import (
    BoardKey,
    BridgeAnchor,
    DdHalfGeometryCapture,
    DirectedLandingSection,
    Edge2P,
    OrderedTerminalSection,
    Point3,
    RxDdBackStubSource,
    TxDdStartStubSource,
    TxSeriesBindingInputs,
    TxVerticalLinkNode,
    _unset_bridge_anchor,
    _unset_directed_landing_section,
    _unset_edge2p,
    _unset_ordered_terminal_section,
    _unset_string,
    _unset_tx_series_binding,
)
from .build_via_ops import _close_stacked_tx_dd_half_conductors_with_hex_vias
from .finalize_pipeline import run_finalize_plan
from .finalize_types import FinalizePlan


_UNSET_LANDING = _unset_directed_landing_section()
_UNSET_EDGE = _unset_edge2p()
_UNSET_SECTION = _unset_ordered_terminal_section()
_UNSET_ANCHOR = _unset_bridge_anchor()
_UNSET_NAME = _unset_string()
_UNSET_TX_SERIES_BINDING = _unset_tx_series_binding()
_EMPTY_COIL_POLARITY = cast(list[CoilPolaritySpec], [])
_EMPTY_DD_HALF_GEOMETRIES = cast(list[DdHalfGeometryCapture], [])


def _run_finalize_plan_with_rotation(
    *,
    modeler: Modeler3D,
    hfss: Hfss,
    aedt_path: Path,
    design_id: str,
    cu_thickness: float,
    pcb_thickness: float,
    via_diameter_mm: float = 0.5,
    tx_board_ids: set[str],
    tx_vertical_nodes_by_board: dict[BoardKey, list[TxVerticalLinkNode]],
    tx_vertical_region_min: Point3,
    tx_vertical_region_max: Point3,
    txdd_right_a_points: dict[int, tuple[Point3, float]],
    txdd_right_object_names: dict[int, str],
    txdd_start_stub_sources: dict[str, list[TxDdStartStubSource]],
    rxdd_back_stub_sources: list[RxDdBackStubSource],
    group_objects: GroupObjects,
    object_names: list[str],
    cad_probe: list[CadProbe],
    placement_violations: list[RegionViolation],
    coil_plane_bboxes: list[tuple[str, Literal["XY", "YZ", "ZX"], list[float]]],
    fr4_object_names: list[str],
    tx_vertical_fr4_names: list[str],
    tx_vertical_orientation_mode: Literal[0, 1] = 1,
    tx_dd_region_min: Point3 = (0.0, 0.0, 0.0),
    tx_dd_region_max: Point3 = (0.0, 0.0, 0.0),
    tx_dd_center_y: float = 0.0,
    coil_polarity: list[CoilPolaritySpec] = _EMPTY_COIL_POLARITY,
    dd_half_geometries: list[DdHalfGeometryCapture] = _EMPTY_DD_HALF_GEOMETRIES,
    txdd_global_right_bridge_landing: DirectedLandingSection = _UNSET_LANDING,
    txdd_global_right_bridge_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_bridge_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_object_name: str = _UNSET_NAME,
    txdd_global_right_d_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_d_object_name: str = _UNSET_NAME,
    tx_vertical_global_outer_right_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_left_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_right_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_left_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_right_section: OrderedTerminalSection = _UNSET_SECTION,
    tx_vertical_global_outer_left_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_right_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_left_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_series_binding: TxSeriesBindingInputs = _UNSET_TX_SERIES_BINDING,
) -> tuple[list[str], list[str], EmPorts, EmPortAssignments, float, Point3, list[str]]:
    artifacts = run_finalize_plan(
        FinalizePlan(
            modeler=modeler,
            hfss=hfss,
            aedt_path=aedt_path,
            design_id=design_id,
            cu_thickness=cu_thickness,
            pcb_thickness=pcb_thickness,
            via_diameter_mm=via_diameter_mm,
            tx_vertical_orientation_mode=tx_vertical_orientation_mode,
            tx_board_ids=tx_board_ids,
            tx_dd_region_min=tx_dd_region_min,
            tx_dd_region_max=tx_dd_region_max,
            tx_dd_center_y=tx_dd_center_y,
            tx_vertical_nodes_by_board=tx_vertical_nodes_by_board,
            tx_vertical_region_min=tx_vertical_region_min,
            tx_vertical_region_max=tx_vertical_region_max,
            txdd_right_a_points=txdd_right_a_points,
            txdd_right_object_names=txdd_right_object_names,
            txdd_start_stub_sources=txdd_start_stub_sources,
            rxdd_back_stub_sources=rxdd_back_stub_sources,
            group_objects=group_objects,
            object_names=object_names,
            cad_probe=cad_probe,
            placement_violations=placement_violations,
            coil_plane_bboxes=coil_plane_bboxes,
            fr4_object_names=fr4_object_names,
            tx_vertical_fr4_names=tx_vertical_fr4_names,
            coil_polarity=coil_polarity,
            dd_half_geometries=dd_half_geometries,
            tx_dd_rotation_angle_deg=0.0,
            tx_dd_rotation_pivot_xyz=(0.0, 0.0, 0.0),
            tx_dd_rotation_object_names=[],
            txdd_global_right_bridge_landing=txdd_global_right_bridge_landing,
            txdd_global_right_bridge_edge=txdd_global_right_bridge_edge,
            txdd_global_right_bridge_section=txdd_global_right_bridge_section,
            txdd_global_right_bridge_object_name=txdd_global_right_bridge_object_name,
            txdd_global_right_d_edge=txdd_global_right_d_edge,
            txdd_global_right_d_object_name=txdd_global_right_d_object_name,
            tx_vertical_global_outer_right_edge=tx_vertical_global_outer_right_edge,
            tx_vertical_global_outer_left_edge=tx_vertical_global_outer_left_edge,
            tx_vertical_global_outer_right_landing=tx_vertical_global_outer_right_landing,
            tx_vertical_global_outer_left_landing=tx_vertical_global_outer_left_landing,
            tx_vertical_global_outer_right_section=tx_vertical_global_outer_right_section,
            tx_vertical_global_outer_left_section=tx_vertical_global_outer_left_section,
            txdd_global_right_bridge_anchor=txdd_global_right_bridge_anchor,
            tx_vertical_global_outer_right_anchor=tx_vertical_global_outer_right_anchor,
            tx_vertical_global_outer_left_anchor=tx_vertical_global_outer_left_anchor,
            tx_series_binding=tx_series_binding,
        ),
        stacked_txdd_closer=_close_stacked_tx_dd_half_conductors_with_hex_vias,
    )
    return (
        artifacts.object_names,
        artifacts.fr4_object_names,
        artifacts.resolved_ports,
        artifacts.resolved_port_assignments,
        artifacts.tx_dd_rotation_angle_deg,
        artifacts.tx_dd_rotation_pivot_xyz,
        artifacts.tx_dd_rotation_object_names,
    )


def _finalize_solids_and_substrates_impl(
    *,
    modeler: Modeler3D,
    hfss: Hfss,
    aedt_path: Path,
    design_id: str,
    cu_thickness: float,
    pcb_thickness: float,
    via_diameter_mm: float = 0.5,
    tx_board_ids: set[str],
    tx_vertical_nodes_by_board: dict[BoardKey, list[TxVerticalLinkNode]],
    tx_vertical_region_min: Point3,
    tx_vertical_region_max: Point3,
    txdd_right_a_points: dict[int, tuple[Point3, float]],
    txdd_right_object_names: dict[int, str],
    txdd_start_stub_sources: dict[str, list[TxDdStartStubSource]],
    rxdd_back_stub_sources: list[RxDdBackStubSource],
    group_objects: GroupObjects,
    object_names: list[str],
    cad_probe: list[CadProbe],
    placement_violations: list[RegionViolation],
    coil_plane_bboxes: list[tuple[str, Literal["XY", "YZ", "ZX"], list[float]]],
    fr4_object_names: list[str],
    tx_vertical_fr4_names: list[str],
    tx_vertical_orientation_mode: Literal[0, 1] = 1,
    tx_dd_region_min: Point3 = (0.0, 0.0, 0.0),
    tx_dd_region_max: Point3 = (0.0, 0.0, 0.0),
    tx_dd_center_y: float = 0.0,
    coil_polarity: list[CoilPolaritySpec] = _EMPTY_COIL_POLARITY,
    dd_half_geometries: list[DdHalfGeometryCapture] = _EMPTY_DD_HALF_GEOMETRIES,
    txdd_global_right_bridge_landing: DirectedLandingSection = _UNSET_LANDING,
    txdd_global_right_bridge_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_bridge_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_object_name: str = _UNSET_NAME,
    txdd_global_right_d_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_d_object_name: str = _UNSET_NAME,
    tx_vertical_global_outer_right_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_left_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_right_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_left_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_right_section: OrderedTerminalSection = _UNSET_SECTION,
    tx_vertical_global_outer_left_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_right_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_left_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_series_binding: TxSeriesBindingInputs = _UNSET_TX_SERIES_BINDING,
) -> tuple[list[str], list[str], EmPorts, EmPortAssignments]:
    object_names_after, fr4_object_names_after, resolved_ports, resolved_port_assignments, _, _, _ = _run_finalize_plan_with_rotation(
        modeler=modeler,
        hfss=hfss,
        aedt_path=aedt_path,
        design_id=design_id,
        cu_thickness=cu_thickness,
        pcb_thickness=pcb_thickness,
        via_diameter_mm=via_diameter_mm,
        tx_board_ids=tx_board_ids,
        tx_vertical_nodes_by_board=tx_vertical_nodes_by_board,
        tx_vertical_region_min=tx_vertical_region_min,
        tx_vertical_region_max=tx_vertical_region_max,
        txdd_right_a_points=txdd_right_a_points,
        txdd_right_object_names=txdd_right_object_names,
        txdd_start_stub_sources=txdd_start_stub_sources,
        rxdd_back_stub_sources=rxdd_back_stub_sources,
        group_objects=group_objects,
        object_names=object_names,
        cad_probe=cad_probe,
        placement_violations=placement_violations,
        coil_plane_bboxes=coil_plane_bboxes,
        fr4_object_names=fr4_object_names,
        tx_vertical_fr4_names=tx_vertical_fr4_names,
        tx_vertical_orientation_mode=tx_vertical_orientation_mode,
        tx_dd_region_min=tx_dd_region_min,
        tx_dd_region_max=tx_dd_region_max,
        tx_dd_center_y=tx_dd_center_y,
        coil_polarity=coil_polarity,
        dd_half_geometries=dd_half_geometries,
        txdd_global_right_bridge_landing=txdd_global_right_bridge_landing,
        txdd_global_right_bridge_edge=txdd_global_right_bridge_edge,
        txdd_global_right_bridge_section=txdd_global_right_bridge_section,
        txdd_global_right_bridge_object_name=txdd_global_right_bridge_object_name,
        txdd_global_right_d_edge=txdd_global_right_d_edge,
        txdd_global_right_d_object_name=txdd_global_right_d_object_name,
        tx_vertical_global_outer_right_edge=tx_vertical_global_outer_right_edge,
        tx_vertical_global_outer_left_edge=tx_vertical_global_outer_left_edge,
        tx_vertical_global_outer_right_landing=tx_vertical_global_outer_right_landing,
        tx_vertical_global_outer_left_landing=tx_vertical_global_outer_left_landing,
        tx_vertical_global_outer_right_section=tx_vertical_global_outer_right_section,
        tx_vertical_global_outer_left_section=tx_vertical_global_outer_left_section,
        txdd_global_right_bridge_anchor=txdd_global_right_bridge_anchor,
        tx_vertical_global_outer_right_anchor=tx_vertical_global_outer_right_anchor,
        tx_vertical_global_outer_left_anchor=tx_vertical_global_outer_left_anchor,
        tx_series_binding=tx_series_binding,
    )
    return object_names_after, fr4_object_names_after, resolved_ports, resolved_port_assignments


def finalize_solids_and_substrates(
    *,
    modeler: Modeler3D,
    hfss: Hfss,
    aedt_path: Path,
    design_id: str,
    cu_thickness: float,
    pcb_thickness: float,
    via_diameter_mm: float = 0.5,
    tx_board_ids: set[str],
    tx_vertical_nodes_by_board: dict[BoardKey, list[TxVerticalLinkNode]],
    tx_vertical_region_min: Point3,
    tx_vertical_region_max: Point3,
    txdd_right_a_points: dict[int, tuple[Point3, float]],
    txdd_right_object_names: dict[int, str],
    txdd_start_stub_sources: dict[str, list[TxDdStartStubSource]],
    rxdd_back_stub_sources: list[RxDdBackStubSource],
    group_objects: GroupObjects,
    object_names: list[str],
    cad_probe: list[CadProbe],
    placement_violations: list[RegionViolation],
    coil_plane_bboxes: list[tuple[str, Literal["XY", "YZ", "ZX"], list[float]]],
    fr4_object_names: list[str],
    tx_vertical_fr4_names: list[str],
    coil_polarity: list[CoilPolaritySpec],
    dd_half_geometries: list[DdHalfGeometryCapture],
    tx_vertical_orientation_mode: Literal[0, 1] = 1,
    tx_dd_region_min: Point3 = (0.0, 0.0, 0.0),
    tx_dd_region_max: Point3 = (0.0, 0.0, 0.0),
    tx_dd_center_y: float = 0.0,
    txdd_global_right_bridge_landing: DirectedLandingSection = _UNSET_LANDING,
    txdd_global_right_bridge_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_bridge_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_object_name: str = _UNSET_NAME,
    txdd_global_right_d_edge: Edge2P = _UNSET_EDGE,
    txdd_global_right_d_object_name: str = _UNSET_NAME,
    tx_vertical_global_outer_right_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_left_edge: Edge2P = _UNSET_EDGE,
    tx_vertical_global_outer_right_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_left_landing: DirectedLandingSection = _UNSET_LANDING,
    tx_vertical_global_outer_right_section: OrderedTerminalSection = _UNSET_SECTION,
    tx_vertical_global_outer_left_section: OrderedTerminalSection = _UNSET_SECTION,
    txdd_global_right_bridge_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_right_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_vertical_global_outer_left_anchor: BridgeAnchor = _UNSET_ANCHOR,
    tx_series_binding: TxSeriesBindingInputs = _UNSET_TX_SERIES_BINDING,
) -> tuple[list[str], list[str], EmPorts, EmPortAssignments, float, Point3, list[str]]:
    return _run_finalize_plan_with_rotation(
        modeler=modeler,
        hfss=hfss,
        aedt_path=aedt_path,
        design_id=design_id,
        cu_thickness=cu_thickness,
        pcb_thickness=pcb_thickness,
        via_diameter_mm=via_diameter_mm,
        tx_vertical_orientation_mode=tx_vertical_orientation_mode,
        tx_board_ids=tx_board_ids,
        tx_dd_region_min=tx_dd_region_min,
        tx_dd_region_max=tx_dd_region_max,
        tx_dd_center_y=tx_dd_center_y,
        tx_vertical_nodes_by_board=tx_vertical_nodes_by_board,
        tx_vertical_region_min=tx_vertical_region_min,
        tx_vertical_region_max=tx_vertical_region_max,
        txdd_right_a_points=txdd_right_a_points,
        txdd_right_object_names=txdd_right_object_names,
        txdd_start_stub_sources=txdd_start_stub_sources,
        rxdd_back_stub_sources=rxdd_back_stub_sources,
        group_objects=group_objects,
        object_names=object_names,
        cad_probe=cad_probe,
        placement_violations=placement_violations,
        coil_plane_bboxes=coil_plane_bboxes,
        fr4_object_names=fr4_object_names,
        tx_vertical_fr4_names=tx_vertical_fr4_names,
        coil_polarity=coil_polarity,
        dd_half_geometries=dd_half_geometries,
        txdd_global_right_bridge_landing=txdd_global_right_bridge_landing,
        txdd_global_right_bridge_edge=txdd_global_right_bridge_edge,
        txdd_global_right_bridge_section=txdd_global_right_bridge_section,
        txdd_global_right_bridge_object_name=txdd_global_right_bridge_object_name,
        txdd_global_right_d_edge=txdd_global_right_d_edge,
        txdd_global_right_d_object_name=txdd_global_right_d_object_name,
        tx_vertical_global_outer_right_edge=tx_vertical_global_outer_right_edge,
        tx_vertical_global_outer_left_edge=tx_vertical_global_outer_left_edge,
        tx_vertical_global_outer_right_landing=tx_vertical_global_outer_right_landing,
        tx_vertical_global_outer_left_landing=tx_vertical_global_outer_left_landing,
        tx_vertical_global_outer_right_section=tx_vertical_global_outer_right_section,
        tx_vertical_global_outer_left_section=tx_vertical_global_outer_left_section,
        txdd_global_right_bridge_anchor=txdd_global_right_bridge_anchor,
        tx_vertical_global_outer_right_anchor=tx_vertical_global_outer_right_anchor,
        tx_vertical_global_outer_left_anchor=tx_vertical_global_outer_left_anchor,
        tx_series_binding=tx_series_binding,
    )


__all__ = ["_finalize_solids_and_substrates_impl", "finalize_solids_and_substrates"]
