from __future__ import annotations

from peetsfea.tx_rect_void_centerline import build_tx_rect_void_centerline
from peetsfea.tx_rect_void_export import (
    _copper_primitives_for_layer,
    build_tx_rect_void_box_specs,
    build_tx_rect_void_step_scene,
    export_tx_rect_void_step,
    export_tx_rect_void_step_from_spec,
    modeled_body_bounds_from_boxes,
)
from peetsfea.tx_rect_void_geometry import (
    RectBounds,
    _offset_join_point,
    _polygon_bounds,
    _segment_joined_polygon,
)
from peetsfea.tx_rect_void_spec import load_tx_rect_void_spec, realize_tx_rect_void_spec
from peetsfea.tx_rect_void_types import (
    BoxSpec,
    ManufacturingSpec,
    ModeledObjectCanonicalCoordinates,
    ModeledObjectEntry,
    ModeledObjectTerminalMetadata,
    RangeSpec,
    RX_SINGLE_COIL_PROFILE,
    RealizedSingleCoilRectVoid,
    SideGeometry,
    SingleCoilRangeSpec,
    SingleCoilRectVoidExportResult,
    SingleCoilRectVoidSpec,
    SingleCoilSideGeometry,
    SingleCoilProfile,
    TerminalPath,
    TX_SINGLE_COIL_PROFILE,
    TX_INNER_SINGLE_COIL_PROFILE,
    TX_PARALLEL_SINGLE_COIL_ROLES,
    profile_for_modeled_role,
)

__all__ = [
    "BoxSpec",
    "ManufacturingSpec",
    "ModeledObjectCanonicalCoordinates",
    "ModeledObjectEntry",
    "ModeledObjectTerminalMetadata",
    "RangeSpec",
    "RectBounds",
    "RX_SINGLE_COIL_PROFILE",
    "SideGeometry",
    "SingleCoilRangeSpec",
    "SingleCoilRectVoidExportResult",
    "SingleCoilRectVoidSpec",
    "SingleCoilSideGeometry",
    "SingleCoilProfile",
    "RealizedSingleCoilRectVoid",
    "TerminalPath",
    "TX_SINGLE_COIL_PROFILE",
    "TX_INNER_SINGLE_COIL_PROFILE",
    "TX_PARALLEL_SINGLE_COIL_ROLES",
    "build_tx_rect_void_box_specs",
    "build_tx_rect_void_centerline",
    "build_tx_rect_void_step_scene",
    "export_tx_rect_void_step",
    "export_tx_rect_void_step_from_spec",
    "load_tx_rect_void_spec",
    "modeled_body_bounds_from_boxes",
    "profile_for_modeled_role",
    "realize_tx_rect_void_spec",
]
